export enum UserRole {
    ADMIN = 'ADMIN',
    PROJECT_MANAGER = 'PROJECT_MANAGER',
    TRADER = 'TRADER',
    PRODUCTION_EMPLOYEE = 'PRODUCTION_EMPLOYEE',
    LOGISTICS_SPECIALIST = 'LOGISTICS_SPECIALIST'
}